target:
- target
continuous_cols:
- feature_0
- feature_1
- feature_2
- feature_3
- feature_4
- feature_5
- feature_6
- feature_7
- feature_8
- feature_9
- feature_10
- feature_11
- feature_12
- feature_13
- feature_14
- feature_15
- feature_16
- feature_17
- feature_18
- feature_19
- feature_20
- feature_21
- feature_22
- feature_23
- feature_24
- feature_25
- feature_26
- feature_27
- feature_28
- feature_29
- feature_30
- feature_31
- feature_32
- feature_33
- feature_34
- feature_35
- feature_36
- feature_37
- feature_38
- feature_39
- feature_40
- feature_41
- feature_42
- feature_43
- feature_44
- feature_45
- feature_46
- feature_47
- feature_48
- feature_49
- feature_50
- feature_51
- feature_52
- feature_53
categorical_cols: []
date_cols: []
encode_date_cols: true
validation_split: 0.2
target_transform: null
continuous_feature_transform: yeo-johnson
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
categorical_dim: 0
continuous_dim: 54
